#!/usr/bin/env bash
set -eu

source config

for node in ${nodes[@]}
do
  sudo ip netns add ${PREFIX}_${node}
done

for sw in ${switches[@]}
do
  sudo brctl addbr ${PREFIX}_$sw
done

for cable in "${cables[@]}"
do
  tmp=(${cable})
  sudo ip link add ${PREFIX}_${tmp[0]}_to_${tmp[1]} type veth peer name ${PREFIX}_${tmp[1]}_to_${tmp[0]}
  if [[ "${tmp[0]}" =~ ^(RT|CE) ]]; then
    sudo ip link set ${PREFIX}_${tmp[0]}_to_${tmp[1]} netns ${PREFIX}_${tmp[0]} up
  else
    sudo brctl addif ${PREFIX}_${tmp[0]} ${PREFIX}_${tmp[0]}_to_${tmp[1]}
    sudo ip link set ${PREFIX}_${tmp[0]}_to_${tmp[1]} up
  fi

  if [[ "${tmp[1]}" =~ ^(RT|CE) ]]; then
    sudo ip link set ${PREFIX}_${tmp[1]}_to_${tmp[0]} netns ${PREFIX}_${tmp[1]} up
  else
    sudo brctl addif ${PREFIX}_${tmp[1]} ${PREFIX}_${tmp[1]}_to_${tmp[0]}
    sudo ip link set ${PREFIX}_${tmp[1]}_to_${tmp[0]} up
  fi
done

for cable in "${cables[@]}"
do
  tmp=($(echo $cable))
  [[ "${tmp[0]}" =~ ^(RT|CE) ]] && sudo ip netns exec ${PREFIX}_${tmp[0]} ip addr add ${tmp[2]} dev ${PREFIX}_${tmp[0]}_to_${tmp[1]}
  [[ "${tmp[1]}" =~ ^(RT|CE) ]] && sudo ip netns exec ${PREFIX}_${tmp[1]} ip addr add ${tmp[3]} dev ${PREFIX}_${tmp[1]}_to_${tmp[0]}
done

for node in ${nodes[@]}
do
  sudo ip netns exec ${PREFIX}_${node} ip addr add 127.0.0.1/8 dev lo
  sudo ip netns exec ${PREFIX}_${node} ip link set lo up
done

for sw in ${switches[@]}
do
  sudo ip link set ${PREFIX}_$sw up
done

