#!/bin/bash
set -eu

for dev in  $(ip link show type veth |grep "_to_" |cut -d' ' -f 2 | cut -d'@' -f1)
do
  sudo ip link delete $dev || :
done

sudo ip link set down SW1

sudo brctl delbr SW1

sudo ip -all netns del
